# Generated by Django 6.0.3 on 2026-03-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0008_complaint_escalating_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='level_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
