# Generated by Django migration for new status field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_app', '0009_complaint_level_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('in_progress', 'In Progress'),
                    ('escalated', 'Escalated'),
                    ('resolved', 'Resolved')
                ],
                default='pending',
                max_length=20
            ),
        ),
    ]
